# Generated by Django 4.2.3 on 2023-08-15 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formapp', '0002_banneduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banreason', models.CharField(max_length=50, verbose_name='nedenler')),
            ],
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='reason',
            field=models.CharField(max_length=50, verbose_name='Sebep'),
        ),
        migrations.AlterField(
            model_name='banneduser',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banned_suspect', to=settings.AUTH_USER_MODEL, verbose_name='Banlanan User'),
        ),
        migrations.AddField(
            model_name='banneduser',
            name='ban_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formapp.ban', verbose_name='Ban Nedeni'),
        ),
    ]
