# Generated by Django 4.2.3 on 2023-08-15 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formapp', '0003_ban_alter_banneduser_reason_alter_banneduser_suspect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banlama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neden', models.CharField(max_length=50, verbose_name='Neden')),
                ('tarih', models.DateField(auto_now=True, verbose_name='tarih')),
                ('banlanan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ban_user', to=settings.AUTH_USER_MODEL, verbose_name='banlanan')),
            ],
        ),
        migrations.CreateModel(
            name='Blok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nedenler', models.CharField(max_length=50, verbose_name='neden')),
            ],
        ),
        migrations.RemoveField(
            model_name='banneduser',
            name='authorizer',
        ),
        migrations.RemoveField(
            model_name='banneduser',
            name='ban_reason',
        ),
        migrations.RemoveField(
            model_name='banneduser',
            name='suspect',
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
        migrations.DeleteModel(
            name='BannedUser',
        ),
        migrations.AddField(
            model_name='banlama',
            name='hazir_neden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.blok', verbose_name='blok'),
        ),
        migrations.AddField(
            model_name='banlama',
            name='yetkili',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='yetkili'),
        ),
    ]
