# Generated by Django 4.2.3 on 2023-08-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_banlama_blok_remove_banneduser_authorizer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banlama',
            name='neden',
            field=models.CharField(blank=True, max_length=50, verbose_name='Neden'),
        ),
    ]
