# Generated by Django 4.2.3 on 2023-08-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_alter_banlama_neden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='not',
            name='image',
            field=models.FileField(blank=True, upload_to='upload'),
        ),
    ]
